#!/bin/bash
#
# BEGIN_COPYRIGHT
#
# This file is part of SciDB.
# Copyright (C) 2008-2013 SciDB, Inc.
#
# SciDB is free software: you can redistribute it and/or modify
# it under the terms of the AFFERO GNU General Public License as published by
# the Free Software Foundation.
#
# SciDB is distributed "AS-IS" AND WITHOUT ANY WARRANTY OF ANY KIND,
# INCLUDING ANY IMPLIED WARRANTY OF MERCHANTABILITY,
# NON-INFRINGEMENT, OR FITNESS FOR A PARTICULAR PURPOSE. See
# the AFFERO GNU General Public License for the complete license terms.
#
# You should have received a copy of the AFFERO GNU General Public License
# along with SciDB.  If not, see <http://www.gnu.org/licenses/agpl-3.0.html>
#
# END_COPYRIGHT
#
set -eu
################################################################
#
# This script will run the command string (passed in)
# using ssh to the hosts listed in the host file
# from the present host.
#
host_file="${1}"
if [ ! -f "${host_file}" ]; then
    echo
    echo "Host file '${host_file}' not found."
    exit 1
fi
shift
command="$*"
if [ -z "${command}" ]; then
    echo
    echo "No command string found."
    exit 1
fi
while read host
do
    echo "ssh $host $command..."
    ssh -n -o StrictHostKeyChecking=no -o BatchMode=yes $host "${command}"
    if [ $? -ne 0 ]; then
	echo
	echo "Problem with ssh '${command}' to $host from $hostname."
	echo "Try again when you have fixed it."
	exit 1
    fi
done < $host_file
