#!/bin/bash
#
# BEGIN_COPYRIGHT
#
# This file is part of SciDB.
# Copyright (C) 2008-2014 SciDB, Inc.
#
# SciDB is free software: you can redistribute it and/or modify
# it under the terms of the AFFERO GNU General Public License as published by
# the Free Software Foundation.
#
# SciDB is distributed "AS-IS" AND WITHOUT ANY WARRANTY OF ANY KIND,
# INCLUDING ANY IMPLIED WARRANTY OF MERCHANTABILITY,
# NON-INFRINGEMENT, OR FITNESS FOR A PARTICULAR PURPOSE. See
# the AFFERO GNU General Public License for the complete license terms.
#
# You should have received a copy of the AFFERO GNU General Public License
# along with SciDB.  If not, see <http://www.gnu.org/licenses/agpl-3.0.html>
#
# END_COPYRIGHT
#
################################################################
# This script checks that a user's .bashrc and .bash_profile
# are writable by that user.
#
# It is called from an ssh into a host as root
# passed the user's name.
#
# While as root it changes permissions on this script
# and the directory this script is in so that the user
# can run it.
# Then root su's as the user and runs this script.
################################################################
set -u
#
if [ `id -u` -eq 0 ]; then
    chmod 755 $(dirname $0)
    chmod 755 "$0"
    su -l $1 -c "$0"
    exit $?
fi
# Check .bashrc is writable
if [ ! -f ~/.bashrc ]; then
    touch ~/.bashrc
    chmod 755 ~/.bashrc
fi
if [ ! -w ~/.bashrc ]; then
    echo ">>> "
    echo ">>> User '$USER' on host '$HOSTNAME' can not write to their own .bashrc file."
    echo ">>> Please fix and try again."
    echo ">>> "
    exit 1
fi
# Check .bash_profile is writable
if [ ! -f ~/.bash_profile ]; then
    touch ~/.bash_profile
    chown ${username} ~/.bash_profile
    chmod 755 ~/.bash_profile
fi
if [ ! -w ~/.bash_profile ]; then
    echo ">>> "
    echo ">>> User '$USER' on host '$HOSTNAME' can not write to their own .bash_profile file."
    echo ">>> Please fix and try again."
    echo ">>> "
    exit 1
fi
exit 0
