#!/bin/bash
#
# BEGIN_COPYRIGHT
#
# This file is part of SciDB.
# Copyright (C) 2008-2014 SciDB, Inc.
#
# SciDB is free software: you can redistribute it and/or modify
# it under the terms of the AFFERO GNU General Public License as published by
# the Free Software Foundation.
#
# SciDB is distributed "AS-IS" AND WITHOUT ANY WARRANTY OF ANY KIND,
# INCLUDING ANY IMPLIED WARRANTY OF MERCHANTABILITY,
# NON-INFRINGEMENT, OR FITNESS FOR A PARTICULAR PURPOSE. See
# the AFFERO GNU General Public License for the complete license terms.
#
# You should have received a copy of the AFFERO GNU General Public License
# along with SciDB.  If not, see <http://www.gnu.org/licenses/agpl-3.0.html>
#
# END_COPYRIGHT
#
set -u
################################################################
# This script will check connectivity between this host
# and all hosts over the SciDB ports.
################################################################
# Global values:
#
################################################################
# Processed values:
MYDIR=`dirname ${0}`
################################################################
# Arguments
host_file="${1}"
min_port="${2}"
max_port="${3}"
if [ ! -f "${host_file}" ]; then
    echo
    echo "Host file '${host_file}' not found."
    exit 1
fi
################################################################
# CHECK SCIDB PORTS TO HOSTS
#
while read host
do
    for p in $(eval echo "{${min_port}..${max_port}}")
    do
	${MYDIR}/check_port ${host} $p
    done
done < ${host_file}
