#!/bin/bash
#
# BEGIN_COPYRIGHT
#
# This file is part of SciDB.
# Copyright (C) 2008-2014 SciDB, Inc.
#
# SciDB is free software: you can redistribute it and/or modify
# it under the terms of the AFFERO GNU General Public License as published by
# the Free Software Foundation.
#
# SciDB is distributed "AS-IS" AND WITHOUT ANY WARRANTY OF ANY KIND,
# INCLUDING ANY IMPLIED WARRANTY OF MERCHANTABILITY,
# NON-INFRINGEMENT, OR FITNESS FOR A PARTICULAR PURPOSE. See
# the AFFERO GNU General Public License for the complete license terms.
#
# You should have received a copy of the AFFERO GNU General Public License
# along with SciDB.  If not, see <http://www.gnu.org/licenses/agpl-3.0.html>
#
# END_COPYRIGHT
#
set -u
#
################################################################
# Processed values:
MYDIR=`dirname ${0}`
################################################################
# ARGUMENT PROCESSING
function usage {
    cat <<EOF


Usage:
$0 -h|--help
$0 <ssh_port> <host_file>
EOF
}
if [ $# -lt 2 ]; then
    echo
    echo "Not enough arguments"
    usage
    exit 1
fi
################################################################
# yes is a hidden arguments
# --yes means just do whatever it takes don't ask
#
yes=0
case "${1}" in
    -h|--help)
	usage
	exit 0
	;;
    -y|--yes)
	yes=1
	shift
	;;
    -*)
	echo
	echo "Unknown switch: '${1}'"
	usage
	exit 1
	;;
esac
if [ $# -lt 2 ]; then
    echo
    echo "Not enough arguments"
    usage
    exit 1
fi
ssh_port="${1}"
host_file="${2}"
if [ ! -f "${host_file}" ]; then
    echo
    echo "No host file at location '${host_file}'."
    exit 1
fi
################################################################
# SETUP SSH KEY
. ${MYDIR}/setup_ssh_key
################################################################
# CHECK SSH TO HOSTS AS ROOT
export SSHPASS=""
. ${MYDIR}/check_ssh_2hosts
