#!/bin/bash
#
# BEGIN_COPYRIGHT
#
# This file is part of SciDB.
# Copyright (C) 2008-2013 SciDB, Inc.
#
# SciDB is free software: you can redistribute it and/or modify
# it under the terms of the AFFERO GNU General Public License as published by
# the Free Software Foundation.
#
# SciDB is distributed "AS-IS" AND WITHOUT ANY WARRANTY OF ANY KIND,
# INCLUDING ANY IMPLIED WARRANTY OF MERCHANTABILITY,
# NON-INFRINGEMENT, OR FITNESS FOR A PARTICULAR PURPOSE. See
# the AFFERO GNU General Public License for the complete license terms.
#
# You should have received a copy of the AFFERO GNU General Public License
# along with SciDB.  If not, see <http://www.gnu.org/licenses/agpl-3.0.html>
#
# END_COPYRIGHT
#
set -eu
################################################################
# This script will modify etc/init.d/shimsvc
# to work in the user's local install tree.
#
# First lets make it easy make it executable
chmod a+x etc/init.d/shimsvc
#
# This removes the override of LD_LIBRARY_PATH
# and sets document root to $SCIDB_ROOT/var/lib/shim/wwwroot
# instead of the default /var/lib/shim/wwwroot
#
sed -i \
-e '/LD_LIBRARY_PATH/d' \
-e '/^SCIDBPORT=$/ i\
DOCROOT="-r \${SCIDB_ROOT}/var/lib/shim/wwwroot"' \
-e 's/\$SCIDBPORT/\$SCIDBPORT \$DOCROOT/g' \
etc/init.d/shimsvc
